export const GET_TWEETS_REQUEST = "GET_TWEETS_REQUEST";
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS";
export const GET_TWEETS_FAIL = "GET_TWEETS_FAIL";

export const POST_TWEET_REQUEST = 'POST_TWEET_REQUEST';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_FAIL = 'POST_TWEET_FAIL';

export const DELETE_TWEET_REQUEST = 'DELETE_TWEET_REQUEST';
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAIL = 'DELETE_TWEET_FAIL';

export const EDIT_TWEET_REQUEST = 'EDIT_TWEET_REQUEST';
export const EDIT_TWEET_SUCCESS = 'EDIT_TWEET_SUCCESS';
export const EDIT_TWEET_FAIL = 'EDIT_TWEET_FAIL';