export const GET_TWEETS = "GET_TWEETS";
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS";
export const GET_TWEETS_FAIL = "GET_TWEETS_FAIL";

export const POST_TWEETS = "POST_TWEETS";
export const DELETE_TWEET = "DELETE_TWEET";
export const EDIT_TWEET = "EDIT_TWEET"